### PR TITLE
Release 1.0.0

### PR DESCRIPTION
**Pull request by mvidner**
This ends up a collecting place for all the little fixes.

1. Do not try to merge changes.
It has little chance of working in the generic case.
This is a change in the API, so we bump the major version.
2. Fixed NameError in AugeasTree#replace_entry ([bsc#1137948](https://bugzilla.suse.com/show_bug.cgi?id=1137948), found thanks to static type checking with [Sorbet](https://sorbet.org/))
3. Toolchain updates:
    - Drop support for Ruby 2.2 and 2.3; add 2.6.
    - Fix latest RuboCop complaints

TODO:
- [x] adapt https://github.com/config-files-api/config_files_api_grub2

### CODE REVIEW

**Comment by mvidner** [comment]
I am not sure whether to remove the argument from the save method. Unused argument vs backward compatibility.

**Comment by jreidinger** [comment]
hard question about removing it. At least we should document that this option do nothing.

**Comment by jreidinger** [comment]
and rubocop do not like it

**Comment by mvidner** [comment]
> hard question about removing it. At least we should document that this option do nothing.

It's not so hard, because I can prove that nobody uses this argument :smile: 

No users in form of gems:
- https://rubygems.org/gems/cfa/reverse_dependencies
- https://rubygems.org/gems/cfa_grub2/reverse_dependencies

So only RPM users remain,
- and YaST has 0 matches: https://github.com/search?q=org%3Ayast+changes_only&type=Code
- as opposed to 3 CFA matches (all in the method signatures): https://github.com/search?q=org%3Aconfig-files-api+changes_only&type=Code

**Comment by mvidner** [comment]
I would go for a breaking change, removing the argument from the method signature.
In reality it will not be breaking because nobody uses that argument. (Famous last words, I know. The Chernobyl engineers like that)

**Comment by jreidinger** [comment]
yes, fine for me. Please make it mergable, add change to changelog and increase major as it is backward incompatible change ( following semver ).

**Comment by mvidner** [comment]
Duh, I didn't actually remove the argument yet ... :man_facepalming:

**Comment by mvidner** [comment]
Adapting cfa_grub2: https://github.com/config-files-api/config_files_api_grub2/pull/24

**Pull request merged**
